# https://app.vagrantup.com/freebsd/boxes/FreeBSD-14.1-RELEASE
Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-14.1-RELEASE"
  config.vm.box_version = "2024.05.31"
  config.vm.provision "file", source: "sync", destination: "/tmp/sync"
end
