
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

# https://app.vagrantup.com/freebsd/boxes/FreeBSD-12.1-RELEASE
Vagrant.configure("2") do |config|

  config.vm.box = "freebsd/FreeBSD-12.1-RELEASE"
  config.vm.box_version = "2019.11.01"

  # Proxmox DHCP host
  config.vm.network "private_network", type: "dhcp", name: "vboxnet1", mac: "080027d8a35e"

  config.vm.provision :shell, path: "bootstrap.sh"

end
