# https://app.vagrantup.com/ubuntu/boxes/focal64
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  end

  config.vm.provision "file", source: "zshrc", destination: "/home/vagrant/.zshrc"
  config.vm.provision :shell, path: "bootstrap.sh"

end
