# https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20210329.1.0
# https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20171025.0.0
# https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20170209.0.0
# https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20170119.1.0
# https://app.vagrantup.com/ubuntu/boxes/xenial64
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end
