# https://app.vagrantup.com/rockylinux/boxes/8/versions/7.0.0
# Rocky Linux 8.7 - As of Jan 22th 2023
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.box_version = "7.0.0"
end
