# https://app.vagrantup.com/rockylinux/boxes/8/versions/5.0.0
# Rocky Linux 8.5 - As of March 28th 2022
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.box_version = "5.0.0"
end
