# https://app.vagrantup.com/rockylinux/boxes/9/versions/1.0.0
# Rocky Linux 9.1 - As of Jan 22th 2023
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "1.0.0"
end
